/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { RuntimeExplorerSnapshot } from '@deepseek-ai/dsh-runtime/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$72756e74696d654578706c6f726572 {
    snapshot: () => Promise<RemoteResult<RuntimeExplorerSnapshot>>
  }
  interface TypertRemoteMap {
    'runtimeExplorer/snapshot': () => Promise<RemoteResult<RuntimeExplorerSnapshot>>
  }
  interface TypertRemoteNamespaceMap {
    'runtimeExplorer': TypertRemoteNamespace$72756e74696d654578706c6f726572
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
