/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_runtime_runtimeExplorer_snapshot_result$schema = z.object({
  'profile': z.union([z.literal(null), z.string()]).readonly(),
  'observedAt': z.number().readonly(),
  'refreshIntervalMs': z.number().readonly(),
  'graph': z.object({
  'nodes': z.array(z.object({
  'id': z.string().readonly(),
  'entryId': z.string().readonly(),
  'moduleName': z.string().readonly(),
  'label': z.string().readonly(),
  'enabled': z.boolean().readonly(),
  'phase': z.union([z.literal(null), z.literal("failed"), z.literal("pending"), z.literal("active"), z.literal("loading"), z.literal("unloading")]).readonly(),
  'provides': z.array(z.string()).readonly(),
  'injects': z.array(z.string()).readonly(),
  'missing': z.array(z.string()).readonly(),
  'effects': z.array(z.string()).readonly(),
  'effectCount': z.number().readonly(),
})).readonly(),
  'edges': z.array(z.object({
  'source': z.string().readonly(),
  'target': z.string().readonly(),
  'services': z.array(z.string()).readonly(),
})).readonly(),
}).readonly(),
  'trace': z.array(z.object({
  'id': z.string().readonly(),
  'sessionId': z.string().readonly(),
  'type': z.string().readonly(),
  'seq': z.number().readonly(),
  'time': z.number().readonly(),
  'lane': z.union([z.literal("user"), z.literal("agent"), z.literal("llm"), z.literal("tool"), z.literal("session")]).readonly(),
  'payloadChars': z.number().readonly(),
  'turn': z.number().readonly().optional(),
  'step': z.number().readonly().optional(),
  'callId': z.string().readonly().optional(),
  'name': z.string().readonly().optional(),
  'outcome': z.string().readonly().optional(),
})).readonly(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-runtime',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-runtime#runtimeExplorer/snapshot',
      service: 'runtimeExplorer',
      namespace: 'runtimeExplorer',
      method: 'snapshot',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-runtime/types#RuntimeExplorerSnapshot',
        schema: _deepseek_ai_dsh_runtime_runtimeExplorer_snapshot_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/runtime/src/index.ts","line":235,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
