/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_runtime_runtimeExplorer_snapshot_result$schema = z.object({
  'schemaVersion': z.literal(3).readonly(),
  'bootId': z.string().readonly(),
  'snapshotSeq': z.number().readonly(),
  'profile': z.union([z.literal(null), z.string()]).readonly(),
  'observedAt': z.number().readonly(),
  'refreshIntervalMs': z.number().readonly(),
  'overview': z.object({
  'status': z.literal("running").readonly(),
  'uptimeMs': z.number().readonly(),
  'contexts': z.number().readonly(),
  'plugins': z.number().readonly(),
  'fibers': z.number().readonly(),
  'turns': z.number().readonly(),
  'active': z.number().readonly(),
  'effects': z.number().readonly(),
  'events': z.number().readonly(),
  'errors': z.number().readonly(),
  'loaderBreakdown': z.object({
  'total': z.number().readonly(),
  'statuses': z.object({
  'pending': z.number().readonly(),
  'active': z.number().readonly(),
  'disposed': z.number().readonly(),
  'failed': z.number().readonly(),
}).readonly(),
  'byType': z.array(z.object({
  'category': z.union([z.literal("core"), z.literal("agent"), z.literal("model"), z.literal("tool"), z.literal("session"), z.literal("interface"), z.literal("extension")]).readonly(),
  'total': z.number().readonly(),
  'pending': z.number().readonly(),
  'active': z.number().readonly(),
  'disposed': z.number().readonly(),
  'failed': z.number().readonly(),
})).readonly(),
}).readonly(),
  'fiberBreakdown': z.object({
  'total': z.number().readonly(),
  'statuses': z.object({
  'pending': z.number().readonly(),
  'active': z.number().readonly(),
  'disposed': z.number().readonly(),
  'failed': z.number().readonly(),
}).readonly(),
  'byType': z.array(z.object({
  'category': z.union([z.literal("core"), z.literal("agent"), z.literal("model"), z.literal("tool"), z.literal("session"), z.literal("interface"), z.literal("extension")]).readonly(),
  'total': z.number().readonly(),
  'pending': z.number().readonly(),
  'active': z.number().readonly(),
  'disposed': z.number().readonly(),
  'failed': z.number().readonly(),
})).readonly(),
}).readonly(),
  'serviceBreakdown': z.object({
  'implementations': z.number().readonly(),
  'total': z.number().readonly(),
  'statuses': z.object({
  'pending': z.number().readonly(),
  'active': z.number().readonly(),
  'disposed': z.number().readonly(),
  'failed': z.number().readonly(),
}).readonly(),
  'byType': z.array(z.object({
  'category': z.union([z.literal("core"), z.literal("agent"), z.literal("model"), z.literal("tool"), z.literal("session"), z.literal("interface"), z.literal("extension")]).readonly(),
  'total': z.number().readonly(),
  'pending': z.number().readonly(),
  'active': z.number().readonly(),
  'disposed': z.number().readonly(),
  'failed': z.number().readonly(),
})).readonly(),
}).readonly(),
}).readonly(),
  'graph': z.object({
  'nodes': z.array(z.object({
  'id': z.string().readonly(),
  'logicalKey': z.string().readonly(),
  'entryId': z.string().readonly(),
  'fiberId': z.string().readonly().optional(),
  'runtimeId': z.string().readonly().optional(),
  'moduleName': z.string().readonly(),
  'label': z.string().readonly(),
  'enabled': z.boolean().readonly(),
  'phase': z.union([z.literal(null), z.literal("failed"), z.literal("pending"), z.literal("active"), z.literal("loading"), z.literal("unloading")]).readonly(),
  'provides': z.array(z.string()).readonly(),
  'injects': z.array(z.string()).readonly(),
  'missing': z.array(z.string()).readonly(),
  'effects': z.array(z.string()).readonly(),
  'effectCount': z.number().readonly(),
})).readonly(),
  'edges': z.array(z.object({
  'id': z.string().readonly(),
  'type': z.literal("injects").readonly(),
  'source': z.string().readonly(),
  'target': z.string().readonly(),
  'services': z.array(z.string()).readonly(),
})).readonly(),
}).readonly(),
  'trace': z.array(z.object({
  'id': z.string().readonly(),
  'sessionId': z.string().readonly(),
  'type': z.string().readonly(),
  'seq': z.number().readonly(),
  'time': z.number().readonly(),
  'lane': z.union([z.literal("agent"), z.literal("tool"), z.literal("session"), z.literal("user"), z.literal("llm")]).readonly(),
  'payloadChars': z.number().readonly(),
  'turn': z.number().readonly().optional(),
  'step': z.number().readonly().optional(),
  'callId': z.string().readonly().optional(),
  'name': z.string().readonly().optional(),
  'outcome': z.string().readonly().optional(),
})).readonly(),
  'capabilities': z.object({
  'fiberInstances': z.boolean().readonly(),
  'ownershipEdges': z.boolean().readonly(),
  'scopes': z.boolean().readonly(),
  'lifecycleTransitions': z.boolean().readonly(),
  'turnPluginAttribution': z.boolean().readonly(),
  'eventDispatch': z.union([z.literal("none"), z.literal("summary"), z.literal("listener")]).readonly(),
  'payloadCapture': z.literal(false).readonly(),
}).readonly(),
  'limits': z.object({
  'transitionLimit': z.number().readonly(),
  'traceEventLimit': z.number().readonly(),
}).readonly(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-runtime',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-runtime#runtimeExplorer/snapshot',
      service: 'runtimeExplorer',
      namespace: 'runtimeExplorer',
      method: 'snapshot',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-runtime/types#RuntimeExplorerSnapshot',
        schema: _deepseek_ai_dsh_runtime_runtimeExplorer_snapshot_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/runtime/src/index.ts","line":431,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
